#!/bin/zsh
/usr/libexec/path_helper -s;
export PATH=$PATH:/opt/homebrew/bin
echo $PATH;
export LANG="$(defaults read -g AppleLanguages | \
  sed '/"/!d;s/["[:space:]]//g;s/-/_/').UTF-8"
export HOMEBREW_CELLAR=/opt/homebrew/Cellar
/opt/homebrew/Cellar/pepys/1.3.1/bin/pepys.sh;